version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /BackEnd
      - /FrontEnd
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types: [minor, patch]
